apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-installer-config
  namespace: node-installer
data:
  install.sh: |
    #!/bin/bash

    # Update and install packages
    sudo mkdir /etc/systemd/system/docker.service.d
    sudo echo "[Service]" > /etc/systemd/system/docker.service.d/http-proxy.conf
    sudo echo "#From ACR" >> /etc/systemd/system/docker.service.d/http-proxy.conf
    sudo systemctl daemon-reload
    sudo systemctl restart docker
